//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDA2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CuaHangITEntities : DbContext
    {
        public CuaHangITEntities()
            : base("name=CuaHangITEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiNhanh> ChiNhanhs { get; set; }
        public virtual DbSet<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DbSet<ChiTietKhoHang> ChiTietKhoHangs { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<HangSX> HangSXes { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<KhoHang> KhoHangs { get; set; }
        public virtual DbSet<LoaiSanPham> LoaiSanPhams { get; set; }
        public virtual DbSet<MSdynamicsnapshotview> MSdynamicsnapshotviews { get; set; }
        public virtual DbSet<MSmerge_dynamic_snapshots> MSmerge_dynamic_snapshots { get; set; }
        public virtual DbSet<MSmerge_partition_groups> MSmerge_partition_groups { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<sysreplserver> sysreplservers { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<ThongTinChiTietSP> ThongTinChiTietSPs { get; set; }
        public virtual DbSet<MSdynamicsnapshotjob> MSdynamicsnapshotjobs { get; set; }
        public virtual DbSet<MSmerge_agent_parameters> MSmerge_agent_parameters { get; set; }
        public virtual DbSet<MSmerge_altsyncpartners> MSmerge_altsyncpartners { get; set; }
        public virtual DbSet<MSmerge_articlehistory> MSmerge_articlehistory { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN1_ChiNhanh> MSmerge_conflict_HTQLCuaHangIT_CN1_ChiNhanh { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN1_ChiTietDonHang> MSmerge_conflict_HTQLCuaHangIT_CN1_ChiTietDonHang { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN1_ChiTietKhoHang> MSmerge_conflict_HTQLCuaHangIT_CN1_ChiTietKhoHang { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN1_ChucVu> MSmerge_conflict_HTQLCuaHangIT_CN1_ChucVu { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN1_DonHang> MSmerge_conflict_HTQLCuaHangIT_CN1_DonHang { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN1_HangSX> MSmerge_conflict_HTQLCuaHangIT_CN1_HangSX { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN1_KhachHang> MSmerge_conflict_HTQLCuaHangIT_CN1_KhachHang { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN1_KhoHang> MSmerge_conflict_HTQLCuaHangIT_CN1_KhoHang { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN1_LoaiSanPham> MSmerge_conflict_HTQLCuaHangIT_CN1_LoaiSanPham { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN1_NhanVien> MSmerge_conflict_HTQLCuaHangIT_CN1_NhanVien { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN1_SanPham> MSmerge_conflict_HTQLCuaHangIT_CN1_SanPham { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN1_TaiKhoan> MSmerge_conflict_HTQLCuaHangIT_CN1_TaiKhoan { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN1_ThongTinChiTietSP> MSmerge_conflict_HTQLCuaHangIT_CN1_ThongTinChiTietSP { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN2_ChiNhanh> MSmerge_conflict_HTQLCuaHangIT_CN2_ChiNhanh { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN2_ChiTietDonHang> MSmerge_conflict_HTQLCuaHangIT_CN2_ChiTietDonHang { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN2_ChiTietKhoHang> MSmerge_conflict_HTQLCuaHangIT_CN2_ChiTietKhoHang { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN2_ChucVu> MSmerge_conflict_HTQLCuaHangIT_CN2_ChucVu { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN2_DonHang> MSmerge_conflict_HTQLCuaHangIT_CN2_DonHang { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN2_HangSX> MSmerge_conflict_HTQLCuaHangIT_CN2_HangSX { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN2_KhachHang> MSmerge_conflict_HTQLCuaHangIT_CN2_KhachHang { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN2_KhoHang> MSmerge_conflict_HTQLCuaHangIT_CN2_KhoHang { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN2_LoaiSanPham> MSmerge_conflict_HTQLCuaHangIT_CN2_LoaiSanPham { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN2_NhanVien> MSmerge_conflict_HTQLCuaHangIT_CN2_NhanVien { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN2_SanPham> MSmerge_conflict_HTQLCuaHangIT_CN2_SanPham { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN2_TaiKhoan> MSmerge_conflict_HTQLCuaHangIT_CN2_TaiKhoan { get; set; }
        public virtual DbSet<MSmerge_conflict_HTQLCuaHangIT_CN2_ThongTinChiTietSP> MSmerge_conflict_HTQLCuaHangIT_CN2_ThongTinChiTietSP { get; set; }
        public virtual DbSet<MSmerge_conflicts_info> MSmerge_conflicts_info { get; set; }
        public virtual DbSet<MSmerge_contents> MSmerge_contents { get; set; }
        public virtual DbSet<MSmerge_current_partition_mappings> MSmerge_current_partition_mappings { get; set; }
        public virtual DbSet<MSmerge_errorlineage> MSmerge_errorlineage { get; set; }
        public virtual DbSet<MSmerge_generation_partition_mappings> MSmerge_generation_partition_mappings { get; set; }
        public virtual DbSet<MSmerge_genhistory> MSmerge_genhistory { get; set; }
        public virtual DbSet<MSmerge_history> MSmerge_history { get; set; }
        public virtual DbSet<MSmerge_identity_range> MSmerge_identity_range { get; set; }
        public virtual DbSet<MSmerge_log_files> MSmerge_log_files { get; set; }
        public virtual DbSet<MSmerge_metadataaction_request> MSmerge_metadataaction_request { get; set; }
        public virtual DbSet<MSmerge_past_partition_mappings> MSmerge_past_partition_mappings { get; set; }
        public virtual DbSet<MSmerge_replinfo> MSmerge_replinfo { get; set; }
        public virtual DbSet<MSmerge_sessions> MSmerge_sessions { get; set; }
        public virtual DbSet<MSmerge_settingshistory> MSmerge_settingshistory { get; set; }
        public virtual DbSet<MSmerge_supportability_settings> MSmerge_supportability_settings { get; set; }
        public virtual DbSet<MSmerge_tombstone> MSmerge_tombstone { get; set; }
        public virtual DbSet<MSrepl_errors> MSrepl_errors { get; set; }
        public virtual DbSet<sysmergearticle> sysmergearticles { get; set; }
        public virtual DbSet<sysmergepartitioninfo> sysmergepartitioninfoes { get; set; }
        public virtual DbSet<sysmergepublication> sysmergepublications { get; set; }
        public virtual DbSet<sysmergeschemaarticle> sysmergeschemaarticles { get; set; }
        public virtual DbSet<sysmergeschemachange> sysmergeschemachanges { get; set; }
        public virtual DbSet<sysmergesubscription> sysmergesubscriptions { get; set; }
        public virtual DbSet<sysmergesubsetfilter> sysmergesubsetfilters { get; set; }
    }
}
