//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDA2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_conflict_HTQLCuaHangIT_CN1_ThongTinChiTietSP
    {
        public int ID_ChiTietSP { get; set; }
        public Nullable<int> id_sanpham { get; set; }
        public string Main { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public string OCUNG { get; set; }
        public string CARD { get; set; }
        public string MANHINH { get; set; }
        public string HEDIEUHANH { get; set; }
        public string PIN { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<System.Guid> origin_datasource_id { get; set; }
    }
}
