//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDA2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_conflict_CuaHangIT_CN2_ThanhToan
    {
        public int IDThanhToan { get; set; }
        public Nullable<int> id_donhang { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public string HinhThuc { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<System.Guid> origin_datasource_id { get; set; }
    }
}
