//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDA2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietKhoHangs = new HashSet<ChiTietKhoHang>();
            this.ThongTinChiTietSPs = new HashSet<ThongTinChiTietSP>();
        }
    
        public int IDSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string Anh { get; set; }
        public string AnhOnl { get; set; }
        public Nullable<decimal> GiaVon { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<decimal> GiaKhuyenMai { get; set; }
        public Nullable<double> Size { get; set; }
        public string MauSac { get; set; }
        public Nullable<int> BaoHanh { get; set; }
        public string ThongTinSanPham { get; set; }
        public Nullable<bool> Hot { get; set; }
        public Nullable<int> id_loaisp { get; set; }
        public Nullable<int> id_hangsx { get; set; }
        public Nullable<decimal> PhanTramDaGiam { get; set; }
        public System.Guid rowguid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietKhoHang> ChiTietKhoHangs { get; set; }
        public virtual HangSX HangSX { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinChiTietSP> ThongTinChiTietSPs { get; set; }
    }
}
